pool:
  vmImage: 'ubuntu-18.04'

container: 'golang:latest'

variables:
  SRC_TF: "https://github.com/hashicorp/terraform"
  SRC_IBX: "https://github.com/infobloxopen/terraform-provider-infoblox"
  IBX_VER: "1.0.1"
  GO111MODULE: "on"

steps:
- script:
    # build ibx provider
    git clone ${SRC_IBX} /tmp/ibxsource
    cd /tmp/ibxsource
    golang make build
    mkdir /tmp/plugins
    mv ./ibxsource/terraform-provider-infoblox /tmp/plugins/terraform-provider-infoblox_v${IBX_VER}

- script:
    # build terraform tools
    git clone ${SRC_TF} /tmp/tfsource
    cd /tmp/tfsource
    go install ./tools/terraform-bundle
    terraform-bundle package -plugin-dir /tmp/plugins /data/terraform-bundle.hcl
    ARTIFACT=`ls ./terraform_*`
    mv ${ARTIFACT} /tmp