pool:
  vmImage: 'ubuntu-18.04'

container: 'golang:latest'

variables:
  SRC_TF: "https://github.com/hashicorp/terraform"
  SRC_IBX: "https://github.com/infobloxopen/terraform-provider-infoblox"
  IBX_VER: "1.0.1"
  GO111MODULE: "on"
  PLUGIN_DIR: /tmp/plugins

steps:
# prep
- bash: mkdir $PLUGIN_DIR

# build ibx provider
- bash: mkdir -p $GOPATH/src/github.com/infobloxopen
- bash: git clone $SRC_IBX $GOPATH/src/github.com/infobloxopen/terraform-provider-infoblox
- bash: cd $GOPATH/src/github.com/infobloxopen/terraform-provider-infoblox
- script: sudo apt install make -y && make build
- bash: ls -la $GOPATH/src/github.com/infobloxopen/terraform-provider-infoblox"
- bash: mv $GOPATH/src/github.com/infobloxopen/terraform-provider-infoblox/terraform-provider-infoblox $PLUGIN_DIR/terraform-provider-infoblox_v$IBX_VER

# build terraform tools
- bash: git clone $SRC_TF /tmp/tfsource
- bash: cd /tmp/tfsource
- bash: go install ./tools/terraform-bundle
- bash: terraform-bundle package -plugin-dir $PLUGIN_DIR /data/terraform-bundle.hcl
- bash: ARTIFACT=`ls ./terraform_*`
- bash: mv $ARTIFACT /tmp
