pool:
  vmImage: 'ubuntu-18.04'

container: 'golang:latest'

variables:
  SRC_TF: "https://github.com/hashicorp/terraform"
  SRC_IBX: "https://github.com/infobloxopen/terraform-provider-infoblox"
  IBX_VER: "1.0.1"
  GO111MODULE: "on"

steps:
# build ibx provider
- bash: git clone ${SRC_IBX} /tmp/ibxsource
- bash: cd /tmp/ibxsource
- bash: make build
- bash: mkdir /tmp/plugins
- bash: mv ./ibxsource/terraform-provider-infoblox /tmp/plugins/terraform-provider-infoblox_v${IBX_VER}

- script:
# build terraform tools
- bash: git clone ${SRC_TF} /tmp/tfsource
- bash: cd /tmp/tfsource
- bash: go install ./tools/terraform-bundle
- bash: terraform-bundle package -plugin-dir /tmp/plugins /data/terraform-bundle.hcl
- bash: ARTIFACT=`ls ./terraform_*`
- bash: mv ${ARTIFACT} /tmp